services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'true'
    volumes:
      - ./vw-data/:/data/
    networks:
      - network_name_here
networks:
  network_name_here:
    external: true
    name: network_name_here