services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /mnt/nas/media/Movies
        target: /media/movies
        read_only: true
      - type: bind
        source: /mnt/nas/media/TV_Shows
        target: /media/tv
        read_only: true
      - type: bind
        source: /mnt/nas/media/Music
        target: /media/music
        read_only: true
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=secure_dns_name_here
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # Hardware acceleration for Raspberry Pi 5
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "105"
    networks:
      - network_name_here

networks:
  network_name_here:
    external: true
    name: network_name_here
