services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=dns_name_here
      - PASSWORD_HASH=hashed_password_here
      - PORT=51821
      - WG_PORT=51820
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - '51820:51820/udp'
      - '51821:51821/tcp'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - network_name_here
networks:
  network_name_here:
    external: true
    name: network_name_here
